/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../common";

export declare namespace AssetTokenization {
  export type NftContractDetailsStruct = {
    farmerAddress: string;
    farmerName: string;
    description: string;
    totalMint: BigNumberish;
    availableMint: BigNumberish;
    price: BigNumberish;
    expirationDate: BigNumberish;
  };

  export type NftContractDetailsStructOutput = [
    string,
    string,
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber
  ] & {
    farmerAddress: string;
    farmerName: string;
    description: string;
    totalMint: BigNumber;
    availableMint: BigNumber;
    price: BigNumber;
    expirationDate: BigNumber;
  };
}

export interface AssetTokenizationInterface extends utils.Interface {
  functions: {
    "availableContract(address)": FunctionFragment;
    "buyNft(address)": FunctionFragment;
    "checkUpkeep(bytes)": FunctionFragment;
    "generateNftContract(string,string,uint256,uint256,uint256)": FunctionFragment;
    "getBuyers()": FunctionFragment;
    "getFarmers()": FunctionFragment;
    "getNftContractDetails(address)": FunctionFragment;
    "performUpkeep(bytes)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "availableContract"
      | "buyNft"
      | "checkUpkeep"
      | "generateNftContract"
      | "getBuyers"
      | "getFarmers"
      | "getNftContractDetails"
      | "performUpkeep"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "availableContract",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "buyNft", values: [string]): string;
  encodeFunctionData(
    functionFragment: "checkUpkeep",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "generateNftContract",
    values: [string, string, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getBuyers", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getFarmers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getNftContractDetails",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "performUpkeep",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "availableContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "buyNft", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "checkUpkeep",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "generateNftContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBuyers", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getFarmers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getNftContractDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "performUpkeep",
    data: BytesLike
  ): Result;

  events: {};
}

export interface AssetTokenization extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: AssetTokenizationInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    availableContract(
      farmer: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    buyNft(
      farmerAddress: string,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    checkUpkeep(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean, string] & { upkeepNeeded: boolean }>;

    generateNftContract(
      _farmerName: string,
      _description: string,
      _totalMint: BigNumberish,
      _price: BigNumberish,
      _expirationDate: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    getBuyers(overrides?: CallOverrides): Promise<[string[]]>;

    getFarmers(overrides?: CallOverrides): Promise<[string[]]>;

    getNftContractDetails(
      farmerAddress: string,
      overrides?: CallOverrides
    ): Promise<[AssetTokenization.NftContractDetailsStructOutput]>;

    performUpkeep(
      arg0: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  availableContract(
    farmer: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  buyNft(
    farmerAddress: string,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  checkUpkeep(
    arg0: BytesLike,
    overrides?: CallOverrides
  ): Promise<[boolean, string] & { upkeepNeeded: boolean }>;

  generateNftContract(
    _farmerName: string,
    _description: string,
    _totalMint: BigNumberish,
    _price: BigNumberish,
    _expirationDate: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  getBuyers(overrides?: CallOverrides): Promise<string[]>;

  getFarmers(overrides?: CallOverrides): Promise<string[]>;

  getNftContractDetails(
    farmerAddress: string,
    overrides?: CallOverrides
  ): Promise<AssetTokenization.NftContractDetailsStructOutput>;

  performUpkeep(
    arg0: BytesLike,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    availableContract(
      farmer: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    buyNft(farmerAddress: string, overrides?: CallOverrides): Promise<void>;

    checkUpkeep(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean, string] & { upkeepNeeded: boolean }>;

    generateNftContract(
      _farmerName: string,
      _description: string,
      _totalMint: BigNumberish,
      _price: BigNumberish,
      _expirationDate: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    getBuyers(overrides?: CallOverrides): Promise<string[]>;

    getFarmers(overrides?: CallOverrides): Promise<string[]>;

    getNftContractDetails(
      farmerAddress: string,
      overrides?: CallOverrides
    ): Promise<AssetTokenization.NftContractDetailsStructOutput>;

    performUpkeep(arg0: BytesLike, overrides?: CallOverrides): Promise<void>;
  };

  filters: {};

  estimateGas: {
    availableContract(
      farmer: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    buyNft(
      farmerAddress: string,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    checkUpkeep(arg0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    generateNftContract(
      _farmerName: string,
      _description: string,
      _totalMint: BigNumberish,
      _price: BigNumberish,
      _expirationDate: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    getBuyers(overrides?: CallOverrides): Promise<BigNumber>;

    getFarmers(overrides?: CallOverrides): Promise<BigNumber>;

    getNftContractDetails(
      farmerAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    performUpkeep(
      arg0: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    availableContract(
      farmer: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    buyNft(
      farmerAddress: string,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    checkUpkeep(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    generateNftContract(
      _farmerName: string,
      _description: string,
      _totalMint: BigNumberish,
      _price: BigNumberish,
      _expirationDate: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    getBuyers(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getFarmers(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getNftContractDetails(
      farmerAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    performUpkeep(
      arg0: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
